name: terbilang
description: Convert number & date to words in any language for Flutter/Dart with simple ways, support for multiple language (id, en, other locale will coming soon)
version: 1.0.5
author: Cacing69<cacingworm69@gmail.com>
homepage: https://github.com/bitstudio-id/Terbilang

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
